import type { Metadata } from "next";
import { K2D } from "next/font/google";
import "./globals.css";
import QueryProvider from "../provider/QueryProvider";

const k2D = K2D({
  variable: "--font-k2d",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${k2D.variable} antialiased font-k2d`}>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
